### PR TITLE
Add animated banners

### PR DESCRIPTION
**Pull request by pivotiiii**
Hey it's me again,
I took a look at how the banners of 3ds software are animated and created a template for an animated banner that can be edited fairly easily. The hardest part is the texture format, but thankfully there are tools available to do the conversion.
How it works:
1. convert a 512x256 png to etc1a4 with [3dstex](https://github.com/Cruel/3dstex) (added .exe dependency)
2. extract the banner.bin created by bannertool with [3dstool](https://github.com/dnasdw/3dstool) (added .exe dependency)
3. parse the extracted banner0.bcmdl to find the texture offset
4. write the etc1a4 image at that offset and update all necessary sizes in the .bcmdl
5. repack the banner.bin with 3dstool
6. proceed as usual

- The new banner assets have to fit inside the purple mask to always be displayed, outside of that will get cut off during the animation, I can upload a .psd template for that.
animation_size_template
- The mask is bigger than what was possible before, so the logos can be displayed bigger as well.
512x256
- The 256x128 files from the assets repo are getting resized to 300x150, which is still safe in the purple area and roughly the same size as the old method with static banners.
300x150
- The `bool self.hascustomboxart` does not get checked anymore to rescale images, rather the image dimensions themselves. This may be a tad slower, but also allows both 512x256 and 256x128 to be mixed in the repo.
- I left the current workflow intact so that it is still available, maybe add an arg for that.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Is there an option where we _don't_ use 3dstex? The author of this program is leaving me a little... iffy. Maybe you weren't in the scene when that whole mess happened.

Perhaps devkitPro's stuff? https://github.com/devkitPro/tex3ds

**Comment by pivotiiii** [comment]
I wasn't aware about the authors past, I changed it to use tex3ds now. It wasn't quite a drop in replacement but easy enough once I figured out that the new tool adds a header to the raw image data.

**Comment by lifehackerhansol** [comment]
Yeah...... I hope that clears up why I asked for the switch.

For clarity, this animated banner section isn't optional, yes? Just need to figure out what I need to set up for the next release.

**Comment by pivotiiii** [comment]
What section are you talking about? Right now it always creates an animated banner but the code for the old banner is still in place, it should be easy to create another arg to select between static and animated.  In theory I could also create a template for static images that can make use of the full 512x256. If you want to accept 512x256 pngs in the asset repo the static code will just resize them down to 256x128 at the moment.

**Comment by lifehackerhansol** [comment]
Yeah I was just wondering if animated banner was a mandatory step rather than an optional one.

Either way is fine with me, I just need to tweak the actions workflow to pull the new apps

**Comment by pivotiiii** [comment]
Ok so I added an arg to generate static banners and put everything into the generator.py since the other .py file was more of a remnant of a different project anyway. I would consider this ready to merge at this point.

**Pull request merged**
